# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recinto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='recinto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cancha_recinto', to='recinto.Recinto'),
            preserve_default=False,
        ),
    ]
