# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recinto', '0002_cancha_recinto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cancha', models.ForeignKey(db_column='cancha', on_delete=django.db.models.deletion.CASCADE, to='recinto.Cancha')),
                ('horario', models.ForeignKey(db_column='horario', on_delete=django.db.models.deletion.CASCADE, to='recinto.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='a',
            field=models.ManyToManyField(through='recinto.Reserva', to='recinto.Cancha'),
        ),
    ]
