# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:55
from __future__ import unicode_literals

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='post',
            name='logo',
            field=ajaximage.fields.AjaxImageField(null=True, verbose_name='image'),
        ),
    ]
