# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0005_auto_20160626_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('ScheduleCourt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_court', to='courts.ScheduleCourt', verbose_name='court')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
