# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesorie', '0001_initial'),
        ('courts', '0005_auto_20160626_1121'),
        ('clubs', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='ScheduleCourt',
        ),
        migrations.AddField(
            model_name='reservations',
            name='res_accesorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_accesorie', to='accesorie.Accesorie'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='res_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_name', to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='res_court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_schedule_court', to='courts.ScheduleCourt'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='res_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_schedule_price', to='courts.ScheduleCourt'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='res_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_schedule_schedule', to='courts.ScheduleCourt', verbose_name='scheduleCourt'),
        ),
    ]
