# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0004_auto_20160704_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='author',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, help_text='creation date', null=True),
        ),
    ]
