# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_slug', models.SlugField(editable=False, null=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts/profile/avatar', verbose_name='Photo')),
                ('location', models.CharField(blank=True, max_length=140, verbose_name='Location')),
                ('about', models.TextField(blank=True, help_text='Maximum 150 Characters', validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='About')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
