# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripci\xf3n')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court', to='clubs.Club', verbose_name='club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
