# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='schedules',
        ),
    ]
