# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_club'),
        ('courts', '0003_remove_court_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='price')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_court', to='courts.Court', verbose_name='court')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_court', to='schedules.Schedule', verbose_name='schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
