# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_schedulecourt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecourt',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_courtyard', to='schedules.Schedule', verbose_name='schedule'),
        ),
    ]
