# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
