# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fecha',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
